# Generated by Django 2.2.9 on 2021-11-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_auto_20211106_0700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noterating",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noteratings",
                to="notes.Note",
            ),
        ),
    ]
