# Generated by Django 2.2.9 on 2021-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_auto_20211106_0657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
