# Generated by Django 3.2.9 on 2021-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_auto_20211107_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
